export default [{
    'created_at': 'Fri Dec 29 19:15:04 +0000 2017',
    'id': 946821889648979968,
    'id_str': '946821889648979968',
    'text': 'The battle is life or death, but that doesn’t mean love plays no part. \n#shifters #menage #paranormal #ebook… https://t.co/61xUthkXFN',
    'truncated': true,
    'entities': {
        'hashtags': [{'text': 'shifters', 'indices': [72, 81]}, {
            'text': 'menage',
            'indices': [82, 89]
        }, {'text': 'paranormal', 'indices': [90, 101]}, {'text': 'ebook', 'indices': [102, 108]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/61xUthkXFN',
            'expanded_url': 'https://twitter.com/i/web/status/946821889648979968',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [110, 133]
        }]
    },
    'source': '<a href="http://www.hootsuite.com" rel="nofollow">Hootsuite</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 723462589,
        'id_str': '723462589',
        'name': 'Lori King',
        'screen_name': 'LoriKingBooks',
        'location': 'Kansas',
        'description': 'Dirtyminded girl with a romantic twist. #BestSelling #Author of #eroticromance. I\'m seducing the world, one book at a time. #supermom #rockstar #spaz',
        'url': 'https://t.co/VzANn1eKtc',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'https://t.co/VzANn1eKtc',
                    'expanded_url': 'https://lorikingbooks.wordpress.com/',
                    'display_url': 'lorikingbooks.wordpress.com',
                    'indices': [0, 23]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 3220,
        'friends_count': 1123,
        'listed_count': 303,
        'created_at': 'Sun Jul 29 05:49:23 +0000 2012',
        'favourites_count': 6772,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 36848,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': '131516',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme14/bg.gif',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme14/bg.gif',
        'profile_background_tile': true,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/968300336610820096/QbpGz2wR_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/968300336610820096/QbpGz2wR_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/723462589/1519695722',
        'profile_link_color': '009999',
        'profile_sidebar_border_color': 'EEEEEE',
        'profile_sidebar_fill_color': 'EFEFEF',
        'profile_text_color': '333333',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946821889648979968',
    'queued_at': 1514574905414,
    'timeline_id': '93bbfe14-eccc-11e7-83cb-d2baae171399'
}, {
    'created_at': 'Fri Dec 29 19:01:00 +0000 2017',
    'id': 946818350285328384,
    'id_str': '946818350285328384',
    'text': 'Hi new tweeps &amp; old.\nHope you\'re having fun\nLove the SO, RTs, and likes.\nVisit my #kindle #author website:… https://t.co/VZpaywm8eg',
    'truncated': true,
    'entities': {
        'hashtags': [{'text': 'kindle', 'indices': [86, 93]}, {'text': 'author', 'indices': [94, 101]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/VZpaywm8eg',
            'expanded_url': 'https://twitter.com/i/web/status/946818350285328384',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [112, 135]
        }]
    },
    'source': '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 930126626968428546,
        'id_str': '930126626968428546',
        'name': 'M. K. Theodoratus',
        'screen_name': 'DemonsplusElves',
        'location': '',
        'description': 'Promo for grumpy #fantasy #writer & #blogger. #read my #book #reviews - https://t.co/I14Cocayva Like my #author page on Facebook https://t.co/k5Au9WZryw',
        'url': 'https://t.co/iTui5BbsZf',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'https://t.co/iTui5BbsZf',
                    'expanded_url': 'http://www.mktheodoratus.com',
                    'display_url': 'mktheodoratus.com',
                    'indices': [0, 23]
                }]
            },
            'description': {
                'urls': [{
                    'url': 'https://t.co/I14Cocayva',
                    'expanded_url': 'http://kaytheod.blogspot.com',
                    'display_url': 'kaytheod.blogspot.com',
                    'indices': [72, 95]
                }, {
                    'url': 'https://t.co/k5Au9WZryw',
                    'expanded_url': 'http://ow.ly/PiqO30gy6FgP',
                    'display_url': 'ow.ly/PiqO30gy6FgP',
                    'indices': [129, 152]
                }]
            }
        },
        'protected': false,
        'followers_count': 939,
        'friends_count': 1158,
        'listed_count': 21,
        'created_at': 'Mon Nov 13 17:34:03 +0000 2017',
        'favourites_count': 385,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 4906,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': '000000',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/930129746205204482/-Ezi_qfj_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/930129746205204482/-Ezi_qfj_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/930126626968428546/1510595498',
        'profile_link_color': '1B95E0',
        'profile_sidebar_border_color': '000000',
        'profile_sidebar_fill_color': '000000',
        'profile_text_color': '000000',
        'profile_use_background_image': false,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946818350285328384',
    'queued_at': 1514574062609,
    'timeline_id': '9d623a16-ecca-11e7-8d44-4cedfceb6227'
}, {
    'created_at': 'Fri Dec 29 18:55:12 +0000 2017',
    'id': 946816890558656512,
    'id_str': '946816890558656512',
    'text': 'Keeper of Her Love #asmsg  #spub #kindle #ibooks  #iartg #ibooks #ibook #kobo #nook #book #romance support #Indie… https://t.co/rJr6Ak51XJ',
    'truncated': true,
    'entities': {
        'hashtags': [{'text': 'asmsg', 'indices': [19, 25]}, {
            'text': 'spub',
            'indices': [27, 32]
        }, {'text': 'kindle', 'indices': [33, 40]}, {'text': 'ibooks', 'indices': [41, 48]}, {
            'text': 'iartg',
            'indices': [50, 56]
        }, {'text': 'ibooks', 'indices': [57, 64]}, {'text': 'ibook', 'indices': [65, 71]}, {
            'text': 'kobo',
            'indices': [72, 77]
        }, {'text': 'nook', 'indices': [78, 83]}, {'text': 'book', 'indices': [84, 89]}, {
            'text': 'romance',
            'indices': [90, 98]
        }, {'text': 'Indie', 'indices': [107, 113]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/rJr6Ak51XJ',
            'expanded_url': 'https://twitter.com/i/web/status/946816890558656512',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [115, 138]
        }]
    },
    'source': '<a href="http://jamesbryronlove.com" rel="nofollow">JamBotBooks</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 133042870,
        'id_str': '133042870',
        'name': 'James Bryron Love',
        'screen_name': 'jamesbryronlove',
        'location': 'Brisbane',
        'description': 'I am an artist , writer , poet and musician\r\n\r\nAuthor of SciFi stories and More...\r\n... I RT and FollowBack',
        'url': 'http://t.co/VcRCvjSJlP',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/VcRCvjSJlP',
                    'expanded_url': 'http://jamesbryronlove.com',
                    'display_url': 'jamesbryronlove.com',
                    'indices': [0, 22]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 55449,
        'friends_count': 52012,
        'listed_count': 3541,
        'created_at': 'Wed Apr 14 21:43:24 +0000 2010',
        'favourites_count': 24,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 539769,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': 'C0DEED',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': true,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/1476486969/me-againCropped_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1476486969/me-againCropped_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/133042870/1403397165',
        'profile_link_color': '0084B4',
        'profile_sidebar_border_color': '000000',
        'profile_sidebar_fill_color': 'DDEEF6',
        'profile_text_color': '333333',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': false,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 2,
    'favorite_count': 1,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946816890558656512',
    'queued_at': 1514573713870,
    'timeline_id': 'cd84d330-ecc9-11e7-839f-4fa7083b68ed'
}, {
    'created_at': 'Fri Dec 29 18:53:35 +0000 2017',
    'id': 946816482876493825,
    'id_str': '946816482876493825',
    'text': 'In love with the woman Thor comics at the moment ❤️ yay for kindle unlimited letting me read them on a subscription… https://t.co/3NT0wTeFRd',
    'truncated': true,
    'entities': {
        'hashtags': [],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/3NT0wTeFRd',
            'expanded_url': 'https://twitter.com/i/web/status/946816482876493825',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [117, 140]
        }]
    },
    'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 25725991,
        'id_str': '25725991',
        'name': 'Shauna Jones 🧡',
        'screen_name': 'Shauna_c_jones',
        'location': 'Newcastle Upon Tyne, England',
        'description': '@ubisoft-TheDivision2 Previous: Guerrilla #RIGSMCL 🌸 #5yearsingames #ubiproud #STEMAmbassador #baftacrew #photographer All views are my own 🤓',
        'url': 'https://t.co/3AWBghpO7r',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'https://t.co/3AWBghpO7r',
                    'expanded_url': 'http://www.instagram.com/scjones_p',
                    'display_url': 'instagram.com/scjones_p',
                    'indices': [0, 23]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 6568,
        'friends_count': 2998,
        'listed_count': 160,
        'created_at': 'Sat Mar 21 20:44:45 +0000 2009',
        'favourites_count': 99997,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': true,
        'verified': false,
        'statuses_count': 39845,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': '000000',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme6/bg.gif',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme6/bg.gif',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/1215332340387524608/jgyJVeSK_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1215332340387524608/jgyJVeSK_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/25725991/1576332836',
        'profile_link_color': 'FF691F',
        'profile_sidebar_border_color': '000000',
        'profile_sidebar_fill_color': '000000',
        'profile_text_color': '000000',
        'profile_use_background_image': false,
        'has_extended_profile': true,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': false,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': {
        'id': '6dd4aeb802da9f28',
        'url': 'https://api.twitter.com/1.1/geo/id/6dd4aeb802da9f28.json',
        'place_type': 'city',
        'name': 'Newcastle Upon Tyne',
        'full_name': 'Newcastle Upon Tyne, England',
        'country_code': 'GB',
        'country': 'United Kingdom',
        'contained_within': [],
        'bounding_box': {
            'type': 'Polygon',
            'coordinates': [[[-1.6937923, 54.960055], [-1.596931, 54.960055], [-1.596931, 55.0240558], [-1.6937923, 55.0240558]]]
        },
        'attributes': {}
    },
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 9,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946816482876493825',
    'queued_at': 1514573616953,
    'timeline_id': '93c07168-ecc9-11e7-8534-d649fa576c81'
}, {
    'created_at': 'Fri Dec 29 18:50:23 +0000 2017',
    'id': 946815679533080577,
    'id_str': '946815679533080577',
    'text': 'Love mystery-romance? A Twist of Oleander: Maddie Malone mystery by T. M. Wallace is now on Kindle Scout. Cast your… https://t.co/wIoi3Bo3vE',
    'truncated': true,
    'entities': {
        'hashtags': [],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/wIoi3Bo3vE',
            'expanded_url': 'https://twitter.com/i/web/status/946815679533080577',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [117, 140]
        }]
    },
    'source': '<a href="https://buffer.com" rel="nofollow">Buffer</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 2361516942,
        'id_str': '2361516942',
        'name': 'Book Tweeters',
        'screen_name': 'TheBookTweeters',
        'location': 'California, USA',
        'description': 'READERS: Follow us for tweets on great ebook deals! ★★ AUTHORS: Promote your books to our network of 500,000+ followers! Learn more: https://t.co/GfA2yA9rGL',
        'url': 'http://t.co/hYpZUyqJHa',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/hYpZUyqJHa',
                    'expanded_url': 'http://BookTweeters.com/tbt',
                    'display_url': 'BookTweeters.com/tbt',
                    'indices': [0, 22]
                }]
            },
            'description': {
                'urls': [{
                    'url': 'https://t.co/GfA2yA9rGL',
                    'expanded_url': 'http://booktweeters.com/tbt',
                    'display_url': 'booktweeters.com/tbt',
                    'indices': [133, 156]
                }]
            }
        },
        'protected': false,
        'followers_count': 237554,
        'friends_count': 186035,
        'listed_count': 2924,
        'created_at': 'Tue Feb 25 19:04:50 +0000 2014',
        'favourites_count': 7945,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 264134,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': '022330',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme15/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme15/bg.png',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/475143806434549760/Y-T0m9Kt_normal.jpeg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/475143806434549760/Y-T0m9Kt_normal.jpeg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2361516942/1402118998',
        'profile_link_color': '0084B4',
        'profile_sidebar_border_color': 'A8C7F7',
        'profile_sidebar_fill_color': 'C0DFEC',
        'profile_text_color': '333333',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 1,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946815679533080577',
    'queued_at': 1514573425228,
    'timeline_id': '217985fe-ecc9-11e7-8dc6-d4c351d7340c'
}, {
    'created_at': 'Fri Dec 29 18:47:25 +0000 2017',
    'id': 946814930430386178,
    'id_str': '946814930430386178',
    'text': '"I love studying the CAGED system; I can see the guitar fretboard in a much clearer way!" https://t.co/beW1lLOvYu… https://t.co/PPGpMqJJbZ',
    'truncated': true,
    'entities': {
        'hashtags': [],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/beW1lLOvYu',
            'expanded_url': 'http://geni.us/TWCAGEDBl',
            'display_url': 'geni.us/TWCAGEDBl',
            'indices': [90, 113]
        }, {
            'url': 'https://t.co/PPGpMqJJbZ',
            'expanded_url': 'https://twitter.com/i/web/status/946814930430386178',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [115, 138]
        }]
    },
    'source': '<a href="https://www.socialoomph.com" rel="nofollow">SocialOomph</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 789328729,
        'id_str': '789328729',
        'name': 'Joseph Alexander',
        'screen_name': 'guitar_joseph',
        'location': 'Manchester, England',
        'description': 'Best-selling guitarist, author, musician, writer and traveller. \n\nCheck out my 30+ guitar books (with over 3000 5* reviews) here: https://t.co/lujGzNHTux',
        'url': 'https://t.co/zoXAmB55MX',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'https://t.co/zoXAmB55MX',
                    'expanded_url': 'http://geni.us/twbook',
                    'display_url': 'geni.us/twbook',
                    'indices': [0, 23]
                }]
            },
            'description': {
                'urls': [{
                    'url': 'https://t.co/lujGzNHTux',
                    'expanded_url': 'http://geni.us/twbio',
                    'display_url': 'geni.us/twbio',
                    'indices': [130, 153]
                }]
            }
        },
        'protected': false,
        'followers_count': 6248,
        'friends_count': 4515,
        'listed_count': 117,
        'created_at': 'Wed Aug 29 13:17:59 +0000 2012',
        'favourites_count': 1195,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 43018,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': '000000',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/863606842668306433/S3BNUll9_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/863606842668306433/S3BNUll9_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/789328729/1408034536',
        'profile_link_color': '1B95E0',
        'profile_sidebar_border_color': '000000',
        'profile_sidebar_fill_color': '000000',
        'profile_text_color': '000000',
        'profile_use_background_image': false,
        'has_extended_profile': true,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 1,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946814930430386178',
    'queued_at': 1514573246858,
    'timeline_id': 'b7287fe8-ecc8-11e7-94ed-d9ff2ce17b37'
}, {
    'created_at': 'Fri Dec 29 18:45:03 +0000 2017',
    'id': 946814338060480512,
    'id_str': '946814338060480512',
    'text': 'Just #Released The #Sequel to My Love Will Never Die #asmsg #ian1 #iartg #kindle https://t.co/w96q4Z6Dgz https://t.co/CjbIQDRz6F',
    'truncated': false,
    'entities': {
        'hashtags': [{'text': 'Released', 'indices': [5, 14]}, {
            'text': 'Sequel',
            'indices': [19, 26]
        }, {'text': 'asmsg', 'indices': [53, 59]}, {'text': 'ian1', 'indices': [60, 65]}, {
            'text': 'iartg',
            'indices': [66, 72]
        }, {'text': 'kindle', 'indices': [73, 80]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/w96q4Z6Dgz',
            'expanded_url': 'http://spangaloo.com/books.php?pid=112',
            'display_url': 'spangaloo.com/books.php?pid=…',
            'indices': [81, 104]
        }],
        'media': [{
            'id': 946814335099088896,
            'id_str': '946814335099088896',
            'indices': [105, 128],
            'media_url': 'http://pbs.twimg.com/media/DSPCnw_UMAATy5b.jpg',
            'media_url_https': 'https://pbs.twimg.com/media/DSPCnw_UMAATy5b.jpg',
            'url': 'https://t.co/CjbIQDRz6F',
            'display_url': 'pic.twitter.com/CjbIQDRz6F',
            'expanded_url': 'https://twitter.com/sherlockesr/status/946814338060480512/photo/1',
            'type': 'photo',
            'sizes': {
                'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                'small': {'w': 600, 'h': 300, 'resize': 'fit'},
                'large': {'w': 600, 'h': 300, 'resize': 'fit'},
                'medium': {'w': 600, 'h': 300, 'resize': 'fit'}
            },
            'features': {'orig': {'faces': []}, 'small': {'faces': []}, 'large': {'faces': []}, 'medium': {'faces': []}}
        }]
    },
    'extended_entities': {
        'media': [{
            'id': 946814335099088896,
            'id_str': '946814335099088896',
            'indices': [105, 128],
            'media_url': 'http://pbs.twimg.com/media/DSPCnw_UMAATy5b.jpg',
            'media_url_https': 'https://pbs.twimg.com/media/DSPCnw_UMAATy5b.jpg',
            'url': 'https://t.co/CjbIQDRz6F',
            'display_url': 'pic.twitter.com/CjbIQDRz6F',
            'expanded_url': 'https://twitter.com/sherlockesr/status/946814338060480512/photo/1',
            'type': 'photo',
            'sizes': {
                'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                'small': {'w': 600, 'h': 300, 'resize': 'fit'},
                'large': {'w': 600, 'h': 300, 'resize': 'fit'},
                'medium': {'w': 600, 'h': 300, 'resize': 'fit'}
            },
            'features': {'orig': {'faces': []}, 'small': {'faces': []}, 'large': {'faces': []}, 'medium': {'faces': []}}
        }]
    },
    'source': '<a href="http://eliza.spangaloo.com" rel="nofollow">ElizaTweetMyImages</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 3020620538,
        'id_str': '3020620538',
        'name': 'Eliza Sherlock',
        'screen_name': 'sherlockesr',
        'location': 'Farmington, CT',
        'description': 'Author of short stories and books',
        'url': 'http://t.co/DFv0UQ61cr',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/DFv0UQ61cr',
                    'expanded_url': 'http://eliza.spangaloo.com',
                    'display_url': 'eliza.spangaloo.com',
                    'indices': [0, 22]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 726,
        'friends_count': 843,
        'listed_count': 8,
        'created_at': 'Sun Feb 15 06:13:12 +0000 2015',
        'favourites_count': 2,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 60412,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': 'C0DEED',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': true,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/586073746219278336/5hGI0vCL_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/586073746219278336/5hGI0vCL_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/3020620538/1428567063',
        'profile_link_color': '0084B4',
        'profile_sidebar_border_color': 'C0DEED',
        'profile_sidebar_fill_color': 'DDEEF6',
        'profile_text_color': '333333',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946814338060480512',
    'queued_at': 1514573105436,
    'timeline_id': '62dd2cb8-ecc8-11e7-8541-b687ee3cc044'
}, {
    'created_at': 'Fri Dec 29 18:40:11 +0000 2017',
    'id': 946813112908476424,
    'id_str': '946813112908476424',
    'text': 'UK &amp; US Kindle Book Bundle Sale! The Love in Provence Trilogy ~ the perfect winter escape. #LakeUnionAuthors… https://t.co/i3rjGRk26a',
    'truncated': true,
    'entities': {
        'hashtags': [{'text': 'LakeUnionAuthors', 'indices': [95, 112]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/i3rjGRk26a',
            'expanded_url': 'https://twitter.com/i/web/status/946813112908476424',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [114, 137]
        }]
    },
    'source': '<a href="http://www.hootsuite.com" rel="nofollow">Hootsuite</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 195251196,
        'id_str': '195251196',
        'name': 'Patricia Sands',
        'screen_name': 'patricia_sands',
        'location': 'Toronto & south of France',
        'description': 'Indie author & proudly signed to #LakeUnion Publishing (Amazon). Addicted to writing about,visiting + photographing the south of #France https://t.co/b2GdKOOD70',
        'url': 'http://t.co/s0nJk2SwNf',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/s0nJk2SwNf',
                    'expanded_url': 'http://patriciasandsauthor.com',
                    'display_url': 'patriciasandsauthor.com',
                    'indices': [0, 22]
                }]
            },
            'description': {
                'urls': [{
                    'url': 'https://t.co/b2GdKOOD70',
                    'expanded_url': 'http://amzn.to/1Htle07',
                    'display_url': 'amzn.to/1Htle07',
                    'indices': [137, 160]
                }]
            }
        },
        'protected': false,
        'followers_count': 6573,
        'friends_count': 6491,
        'listed_count': 407,
        'created_at': 'Sun Sep 26 05:52:25 +0000 2010',
        'favourites_count': 1798,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 49810,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': 'DBE9ED',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/656422084361461760/UCb0gaxi_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/656422084361461760/UCb0gaxi_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/195251196/1578622317',
        'profile_link_color': 'CC3366',
        'profile_sidebar_border_color': 'DBE9ED',
        'profile_sidebar_fill_color': 'E6F6F9',
        'profile_text_color': '333333',
        'profile_use_background_image': false,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 2,
    'favorite_count': 4,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946813112908476424',
    'queued_at': 1514572813206,
    'timeline_id': 'b4ae5cb6-ecc7-11e7-9089-1871e2671535'
}, {
    'created_at': 'Fri Dec 29 18:36:12 +0000 2017',
    'id': 946812107541975041,
    'id_str': '946812107541975041',
    'text': '"The Blue #Fairy appeared/held up her #crystal wand &amp; softly spoke. Do not despair. #Hope is not lost.I can grant y… https://t.co/ybaDB6krO0',
    'truncated': true,
    'entities': {
        'hashtags': [{'text': 'Fairy', 'indices': [10, 16]}, {
            'text': 'crystal',
            'indices': [38, 46]
        }, {'text': 'Hope', 'indices': [88, 93]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/ybaDB6krO0',
            'expanded_url': 'https://twitter.com/i/web/status/946812107541975041',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [121, 144]
        }]
    },
    'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 918871471727951872,
        'id_str': '918871471727951872',
        'name': 'Stella',
        'screen_name': 'lava_roe',
        'location': 'Paradise Valley, AZ',
        'description': 'https://t.co/r0hIrldveE',
        'url': null,
        'entities': {
            'description': {
                'urls': [{
                    'url': 'https://t.co/r0hIrldveE',
                    'expanded_url': 'https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias=stripbooks&field-keywords=stella+renee+ervanian+halo+publishing+international',
                    'display_url': 'amazon.com/s/ref=nb_sb_no…',
                    'indices': [0, 23]
                }]
            }
        },
        'protected': false,
        'followers_count': 4271,
        'friends_count': 1536,
        'listed_count': 8,
        'created_at': 'Fri Oct 13 16:10:05 +0000 2017',
        'favourites_count': 29815,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 756,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': 'F5F8FA',
        'profile_background_image_url': null,
        'profile_background_image_url_https': null,
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/918904965002813440/MZCH8UWb_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/918904965002813440/MZCH8UWb_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/918871471727951872/1507919288',
        'profile_link_color': '1DA1F2',
        'profile_sidebar_border_color': 'C0DEED',
        'profile_sidebar_fill_color': 'DDEEF6',
        'profile_text_color': '333333',
        'profile_use_background_image': true,
        'has_extended_profile': true,
        'default_profile': true,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 1,
    'favorite_count': 7,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946812107541975041',
    'queued_at': 1514572573598,
    'timeline_id': '25dd1518-ecc7-11e7-9f97-b4f4fffa1832'
}, {
    'created_at': 'Fri Dec 29 18:32:49 +0000 2017',
    'id': 946811256484319232,
    'id_str': '946811256484319232',
    'text': 'They even stole my weapons; I feel like I am living in a prison. https://t.co/MzmiNG5gFw #Vampire #Books #love… https://t.co/c22wMk4c9e',
    'truncated': true,
    'entities': {
        'hashtags': [{'text': 'Vampire', 'indices': [89, 97]}, {
            'text': 'Books',
            'indices': [98, 104]
        }, {'text': 'love', 'indices': [105, 110]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/MzmiNG5gFw',
            'expanded_url': 'http://amzn.to/1AQj2wq',
            'display_url': 'amzn.to/1AQj2wq',
            'indices': [65, 88]
        }, {
            'url': 'https://t.co/c22wMk4c9e',
            'expanded_url': 'https://twitter.com/i/web/status/946811256484319232',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [112, 135]
        }]
    },
    'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 281270845,
        'id_str': '281270845',
        'name': 'Shadow Ink Press',
        'screen_name': 'shadowinkpress',
        'location': 'Cairns, Australia',
        'description': 'Publishing representative for Australian author Kristy Berridge and publishing house for Indie fiction and promotional specialists',
        'url': 'https://t.co/ysoNcW709g',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'https://t.co/ysoNcW709g',
                    'expanded_url': 'http://www.shadowinkpress.com.au',
                    'display_url': 'shadowinkpress.com.au',
                    'indices': [0, 23]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 8052,
        'friends_count': 6215,
        'listed_count': 2785,
        'created_at': 'Tue Apr 12 23:59:32 +0000 2011',
        'favourites_count': 4315,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 553953,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': '000000',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme9/bg.gif',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme9/bg.gif',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/738880428984000512/k_2norhv_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/738880428984000512/k_2norhv_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/281270845/1470611887',
        'profile_link_color': '990000',
        'profile_sidebar_border_color': '000000',
        'profile_sidebar_fill_color': '000000',
        'profile_text_color': '000000',
        'profile_use_background_image': false,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946811256484319232',
    'queued_at': 1514572370688,
    'timeline_id': 'aceb82b6-ecc6-11e7-98fa-ca2dd583cfd2'
}, {
    'created_at': 'Fri Dec 29 18:31:41 +0000 2017',
    'id': 946810971640578048,
    'id_str': '946810971640578048',
    'text': 'Check out this dark tale of strange love. Thirty. \nRead for free on Kindle Unlimited\nhttps://t.co/Z0UF8Mey6V',
    'truncated': false,
    'entities': {
        'hashtags': [],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/Z0UF8Mey6V',
            'expanded_url': 'https://www.amazon.com/dp/B075LLQQRQ/ref=cm_sw_r_cp_awdb_ajPUzb9P2BBJA',
            'display_url': 'amazon.com/dp/B075LLQQRQ/…',
            'indices': [85, 108]
        }]
    },
    'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 36771404,
        'id_str': '36771404',
        'name': 'superwriter',
        'screen_name': 'MSydnorJr',
        'location': 'Sacramento, CA',
        'description': 'Author. Coffee addict ☕. Hooper 🏀. Visit my Short Story Gallery in the link below. ✌🏽❤',
        'url': 'https://t.co/wmBcU05bl5',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'https://t.co/wmBcU05bl5',
                    'expanded_url': 'https://msydnorjr.com/',
                    'display_url': 'msydnorjr.com',
                    'indices': [0, 23]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 3725,
        'friends_count': 2816,
        'listed_count': 63,
        'created_at': 'Thu Apr 30 21:01:13 +0000 2009',
        'favourites_count': 17537,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 21066,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': 'C0DEED',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': true,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/1033035681440784384/_Mm4Ywpc_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1033035681440784384/_Mm4Ywpc_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/36771404/1529374315',
        'profile_link_color': '0084B4',
        'profile_sidebar_border_color': 'C0DEED',
        'profile_sidebar_fill_color': 'DDEEF6',
        'profile_text_color': '333333',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': false,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 2,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946810971640578048',
    'queued_at': 1514572302282,
    'timeline_id': '84258782-ecc6-11e7-9afa-a65da5f61a34'
}, {
    'created_at': 'Fri Dec 29 18:13:23 +0000 2017',
    'id': 946806367112884225,
    'id_str': '946806367112884225',
    'text': 'Satisfy your love for romance with these sultry seaside tales.\nhttps://t.co/XEgHcTY0kj\n\n#kindle #KindleUnlimited #ku #amreading',
    'truncated': false,
    'entities': {
        'hashtags': [{'text': 'kindle', 'indices': [88, 95]}, {
            'text': 'KindleUnlimited',
            'indices': [96, 112]
        }, {'text': 'ku', 'indices': [113, 116]}, {'text': 'amreading', 'indices': [117, 127]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/XEgHcTY0kj',
            'expanded_url': 'http://www.tracihall.com/by-the-sea/',
            'display_url': 'tracihall.com/by-the-sea/',
            'indices': [63, 86]
        }]
    },
    'source': '<a href="https://www.socialoomph.com" rel="nofollow">SocialOomph</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 37102181,
        'id_str': '37102181',
        'name': 'Traci Hall',
        'screen_name': 'tracihallauthor',
        'location': 'Lauderdale by the Sea',
        'description': 'USA Today best-selling romance author, food lover, coffee addict, wine enthusiast',
        'url': 'http://t.co/Y3ecqbNFov',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/Y3ecqbNFov',
                    'expanded_url': 'http://www.tracihall.com',
                    'display_url': 'tracihall.com',
                    'indices': [0, 22]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 5050,
        'friends_count': 5132,
        'listed_count': 567,
        'created_at': 'Sat May 02 01:25:50 +0000 2009',
        'favourites_count': 1370,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': true,
        'verified': false,
        'statuses_count': 112871,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': '000000',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme10/bg.gif',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme10/bg.gif',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/1828994002/IMG_1151_pp_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1828994002/IMG_1151_pp_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/37102181/1366237442',
        'profile_link_color': 'ABB8C2',
        'profile_sidebar_border_color': '000000',
        'profile_sidebar_fill_color': '000000',
        'profile_text_color': '000000',
        'profile_use_background_image': false,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 2,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946806367112884225',
    'queued_at': 1514571204858,
    'timeline_id': 'f607efdc-ecc3-11e7-89a4-8d8e31085175'
}, {
    'created_at': 'Fri Dec 29 18:08:46 +0000 2017',
    'id': 946805206150299649,
    'id_str': '946805206150299649',
    'text': 'WHAT WILL YOU BE READING THIS HOLIDAY WEEKEND? \n"FIVE STARS!" "A MUST-READ FOR COLLAPSE SERIES FANS!" "I AM SO IN L… https://t.co/sQL3XQdseP',
    'truncated': true,
    'entities': {
        'hashtags': [],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/sQL3XQdseP',
            'expanded_url': 'https://twitter.com/i/web/status/946805206150299649',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [117, 140]
        }]
    },
    'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 129886742,
        'id_str': '129886742',
        'name': 'Summer Lane',
        'screen_name': 'SummerEllenLane',
        'location': 'California, USA',
        'description': '#1 bestselling author of 25+ books, including the hit Collapse Series. Business owner. Wife and mommy. College student. Coffee drinker. https://t.co/YjeZAjqtdw',
        'url': 'https://t.co/UPf5JRZmeW',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'https://t.co/UPf5JRZmeW',
                    'expanded_url': 'https://www.amazon.com/gp/product/B01K4UT7JU/ref=series_rw_dp_sw',
                    'display_url': 'amazon.com/gp/product/B01…',
                    'indices': [0, 23]
                }]
            },
            'description': {
                'urls': [{
                    'url': 'https://t.co/YjeZAjqtdw',
                    'expanded_url': 'http://summerlaneauthor.com',
                    'display_url': 'summerlaneauthor.com',
                    'indices': [136, 159]
                }]
            }
        },
        'protected': false,
        'followers_count': 7498,
        'friends_count': 8368,
        'listed_count': 201,
        'created_at': 'Mon Apr 05 18:19:11 +0000 2010',
        'favourites_count': 2410,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 18481,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': 'FCEBB6',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme15/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme15/bg.png',
        'profile_background_tile': true,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/1129826146529435648/4riJSBX-_normal.png',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1129826146529435648/4riJSBX-_normal.png',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/129886742/1509032774',
        'profile_link_color': 'B87106',
        'profile_sidebar_border_color': 'F0A830',
        'profile_sidebar_fill_color': '78C0A8',
        'profile_text_color': '5E412F',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 1,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946805206150299649',
    'queued_at': 1514570927683,
    'timeline_id': '50d25e3a-ecc3-11e7-9ad4-0670044b2117'
}, {
    'created_at': 'Fri Dec 29 18:02:09 +0000 2017',
    'id': 946803539111763969,
    'id_str': '946803539111763969',
    'text': '• Dana Marton: #PreOrder today - SILENT THREAT releases January 2nd! When an injured former Navy SEAL goes undercov… https://t.co/PY6pGwZJ4T',
    'truncated': true,
    'entities': {
        'hashtags': [{'text': 'PreOrder', 'indices': [15, 24]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/PY6pGwZJ4T',
            'expanded_url': 'https://twitter.com/i/web/status/946803539111763969',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [117, 140]
        }]
    },
    'source': '<a href="http://askdavid.com" rel="nofollow">AskDavid.com Services</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 250309546,
        'id_str': '250309546',
        'name': 'Book Promotion #ad',
        'screen_name': 'book_tribe',
        'location': 'Here, There and Everywhere',
        'description': 'Authors, Writers - Get Promotion For Your Books. Readers find great new books to read.\r\nhttp://t.co/ZGs4k2mupm',
        'url': 'http://t.co/Keael1i1mV',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/Keael1i1mV',
                    'expanded_url': 'http://askDavid.com',
                    'display_url': 'askDavid.com',
                    'indices': [0, 22]
                }]
            },
            'description': {
                'urls': [{
                    'url': 'http://t.co/ZGs4k2mupm',
                    'expanded_url': 'http://askdavid.com/book-promotion',
                    'display_url': 'askdavid.com/book-promotion',
                    'indices': [88, 110]
                }]
            }
        },
        'protected': false,
        'followers_count': 57653,
        'friends_count': 39293,
        'listed_count': 1917,
        'created_at': 'Thu Feb 10 21:01:39 +0000 2011',
        'favourites_count': 308,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 349841,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': '131516',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme14/bg.gif',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme14/bg.gif',
        'profile_background_tile': true,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/605116406724706304/3zmRL_LG_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/605116406724706304/3zmRL_LG_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/250309546/1402513767',
        'profile_link_color': '009999',
        'profile_sidebar_border_color': 'EEEEEE',
        'profile_sidebar_fill_color': 'EFEFEF',
        'profile_text_color': '333333',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 3,
    'favorite_count': 2,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946803539111763969',
    'queued_at': 1514570531079,
    'timeline_id': '646d749e-ecc2-11e7-8864-bdbfaa1f47d8'
}, {
    'created_at': 'Fri Dec 29 18:00:57 +0000 2017',
    'id': 946803236853440512,
    'id_str': '946803236853440512',
    'text': 'Love turns nasty, in Mayhem and Mutiny #kindle #ebook https://t.co/XQHalGdjaL https://t.co/FqpWKC99NT',
    'truncated': false,
    'entities': {
        'hashtags': [{'text': 'kindle', 'indices': [39, 46]}, {'text': 'ebook', 'indices': [47, 53]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/XQHalGdjaL',
            'expanded_url': 'http://amzn.to/2y6Iv60',
            'display_url': 'amzn.to/2y6Iv60',
            'indices': [54, 77]
        }],
        'media': [{
            'id': 946803232088690690,
            'id_str': '946803232088690690',
            'indices': [78, 101],
            'media_url': 'http://pbs.twimg.com/media/DSO4hfDWkAIY5gB.jpg',
            'media_url_https': 'https://pbs.twimg.com/media/DSO4hfDWkAIY5gB.jpg',
            'url': 'https://t.co/FqpWKC99NT',
            'display_url': 'pic.twitter.com/FqpWKC99NT',
            'expanded_url': 'https://twitter.com/CharissaDufour/status/946803236853440512/photo/1',
            'type': 'photo',
            'sizes': {
                'medium': {'w': 749, 'h': 1200, 'resize': 'fit'},
                'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                'large': {'w': 1278, 'h': 2048, 'resize': 'fit'},
                'small': {'w': 424, 'h': 680, 'resize': 'fit'}
            },
            'features': {
                'medium': {
                    'faces': [{'x': 213, 'y': 102, 'h': 122, 'w': 122}, {
                        'x': 38,
                        'y': 316,
                        'h': 122,
                        'w': 122
                    }, {'x': 602, 'y': 406, 'h': 136, 'w': 136}, {'x': 244, 'y': 296, 'h': 277, 'w': 277}]
                },
                'orig': {
                    'faces': [{'x': 444, 'y': 214, 'h': 256, 'w': 256}, {
                        'x': 80,
                        'y': 659,
                        'h': 256,
                        'w': 256
                    }, {'x': 1254, 'y': 847, 'h': 285, 'w': 285}, {'x': 510, 'y': 617, 'h': 578, 'w': 578}]
                },
                'large': {
                    'faces': [{'x': 363, 'y': 175, 'h': 209, 'w': 209}, {
                        'x': 65,
                        'y': 539,
                        'h': 209,
                        'w': 209
                    }, {'x': 1027, 'y': 693, 'h': 233, 'w': 233}, {'x': 417, 'y': 505, 'h': 473, 'w': 473}]
                },
                'small': {
                    'faces': [{'x': 120, 'y': 58, 'h': 69, 'w': 69}, {
                        'x': 21,
                        'y': 179,
                        'h': 69,
                        'w': 69
                    }, {'x': 340, 'y': 230, 'h': 77, 'w': 77}, {'x': 138, 'y': 167, 'h': 157, 'w': 157}]
                }
            }
        }]
    },
    'extended_entities': {
        'media': [{
            'id': 946803232088690690,
            'id_str': '946803232088690690',
            'indices': [78, 101],
            'media_url': 'http://pbs.twimg.com/media/DSO4hfDWkAIY5gB.jpg',
            'media_url_https': 'https://pbs.twimg.com/media/DSO4hfDWkAIY5gB.jpg',
            'url': 'https://t.co/FqpWKC99NT',
            'display_url': 'pic.twitter.com/FqpWKC99NT',
            'expanded_url': 'https://twitter.com/CharissaDufour/status/946803236853440512/photo/1',
            'type': 'photo',
            'sizes': {
                'medium': {'w': 749, 'h': 1200, 'resize': 'fit'},
                'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                'large': {'w': 1278, 'h': 2048, 'resize': 'fit'},
                'small': {'w': 424, 'h': 680, 'resize': 'fit'}
            },
            'features': {
                'medium': {
                    'faces': [{'x': 213, 'y': 102, 'h': 122, 'w': 122}, {
                        'x': 38,
                        'y': 316,
                        'h': 122,
                        'w': 122
                    }, {'x': 602, 'y': 406, 'h': 136, 'w': 136}, {'x': 244, 'y': 296, 'h': 277, 'w': 277}]
                },
                'orig': {
                    'faces': [{'x': 444, 'y': 214, 'h': 256, 'w': 256}, {
                        'x': 80,
                        'y': 659,
                        'h': 256,
                        'w': 256
                    }, {'x': 1254, 'y': 847, 'h': 285, 'w': 285}, {'x': 510, 'y': 617, 'h': 578, 'w': 578}]
                },
                'large': {
                    'faces': [{'x': 363, 'y': 175, 'h': 209, 'w': 209}, {
                        'x': 65,
                        'y': 539,
                        'h': 209,
                        'w': 209
                    }, {'x': 1027, 'y': 693, 'h': 233, 'w': 233}, {'x': 417, 'y': 505, 'h': 473, 'w': 473}]
                },
                'small': {
                    'faces': [{'x': 120, 'y': 58, 'h': 69, 'w': 69}, {
                        'x': 21,
                        'y': 179,
                        'h': 69,
                        'w': 69
                    }, {'x': 340, 'y': 230, 'h': 77, 'w': 77}, {'x': 138, 'y': 167, 'h': 157, 'w': 157}]
                }
            }
        }]
    },
    'source': '<a href="https://www.socialjukebox.com" rel="nofollow">The Social Jukebox</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 1697715858,
        'id_str': '1697715858',
        'name': 'CharissaDufourAuthor',
        'screen_name': 'CharissaDufour',
        'location': 'Chicago, IL',
        'description': 'Unfinished Christian. Brilliant #author, blossoming environmentalist, occasionally-accurate movie quoter, unstable dancer, and life-threatening chef. No DMs. TY',
        'url': null,
        'entities': {'description': {'urls': []}},
        'protected': false,
        'followers_count': 23829,
        'friends_count': 21722,
        'listed_count': 1227,
        'created_at': 'Sun Aug 25 00:25:55 +0000 2013',
        'favourites_count': 24278,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': true,
        'verified': false,
        'statuses_count': 194104,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': '89C9FA',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme9/bg.gif',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme9/bg.gif',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/1116803162495700993/0SQkpw-f_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1116803162495700993/0SQkpw-f_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1697715858/1556639790',
        'profile_link_color': '2FC2EF',
        'profile_sidebar_border_color': '000000',
        'profile_sidebar_fill_color': '000000',
        'profile_text_color': '000000',
        'profile_use_background_image': true,
        'has_extended_profile': true,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946803236853440512',
    'queued_at': 1514570458813,
    'timeline_id': '395a994e-ecc2-11e7-8441-c5abf2569ae3'
}, {
    'created_at': 'Fri Dec 29 17:56:23 +0000 2017',
    'id': 946802087958142978,
    'id_str': '946802087958142978',
    'text': 'Load up your Kindle with some romance! #romance #amreading #kindle #contemporaryromance #love… https://t.co/zKAIbeHv6U',
    'truncated': false,
    'entities': {
        'hashtags': [{'text': 'romance', 'indices': [39, 47]}, {
            'text': 'amreading',
            'indices': [48, 58]
        }, {'text': 'kindle', 'indices': [59, 66]}, {
            'text': 'contemporaryromance',
            'indices': [67, 87]
        }, {'text': 'love', 'indices': [88, 93]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/zKAIbeHv6U',
            'expanded_url': 'https://www.instagram.com/p/BdS5mJcDFK2/',
            'display_url': 'instagram.com/p/BdS5mJcDFK2/',
            'indices': [95, 118]
        }]
    },
    'source': '<a href="http://instagram.com" rel="nofollow">Instagram</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 55284917,
        'id_str': '55284917',
        'name': 'Jannie Lund',
        'screen_name': 'jannielund',
        'location': 'Denmark',
        'description': 'Chaser of shadows and deadlines. Romance author, dreamer, and occasional recluse.',
        'url': 'https://t.co/wEc8HMBWiL',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'https://t.co/wEc8HMBWiL',
                    'expanded_url': 'http://www.jannielund.com',
                    'display_url': 'jannielund.com',
                    'indices': [0, 23]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 874,
        'friends_count': 292,
        'listed_count': 52,
        'created_at': 'Thu Jul 09 16:34:32 +0000 2009',
        'favourites_count': 1146,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 12644,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': 'FFFFFF',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme9/bg.gif',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme9/bg.gif',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/1148269558853263360/LZJgHR84_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1148269558853263360/LZJgHR84_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/55284917/1471083232',
        'profile_link_color': '363636',
        'profile_sidebar_border_color': '696969',
        'profile_sidebar_fill_color': '000000',
        'profile_text_color': '696969',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946802087958142978',
    'queued_at': 1514570184344,
    'timeline_id': '95c1e576-ecc1-11e7-99dc-6bed91c3052e'
}, {
    'created_at': 'Fri Dec 29 17:55:33 +0000 2017',
    'id': 946801878649790464,
    'id_str': '946801878649790464',
    'text': 'Love in the Autumn of Life   https://t.co/99FCS9B7AE\n #Mallorca #debk #99c #kindle #amazon #Majorca #Romance https://t.co/FmY3K9NUCI',
    'truncated': false,
    'entities': {
        'hashtags': [{'text': 'Mallorca', 'indices': [54, 63]}, {'text': 'debk', 'indices': [64, 69]}, {
            'text': '99c',
            'indices': [70, 74]
        }, {'text': 'kindle', 'indices': [75, 82]}, {'text': 'amazon', 'indices': [83, 90]}, {
            'text': 'Majorca',
            'indices': [91, 99]
        }, {'text': 'Romance', 'indices': [100, 108]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/99FCS9B7AE',
            'expanded_url': 'https://www.amazon.de/September-Sun-Kindle-Single-English-ebook/dp/B01L0FKWP6/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1472402197&sr=1-1&keywords=September+Sun',
            'display_url': 'amazon.de/September-Sun-…',
            'indices': [29, 52]
        }],
        'media': [{
            'id': 946801863734759424,
            'id_str': '946801863734759424',
            'indices': [109, 132],
            'media_url': 'http://pbs.twimg.com/media/DSO3R1iWkAAqOCG.jpg',
            'media_url_https': 'https://pbs.twimg.com/media/DSO3R1iWkAAqOCG.jpg',
            'url': 'https://t.co/FmY3K9NUCI',
            'display_url': 'pic.twitter.com/FmY3K9NUCI',
            'expanded_url': 'https://twitter.com/EvaFarohi/status/946801878649790464/photo/1',
            'type': 'photo',
            'sizes': {
                'small': {'w': 144, 'h': 230, 'resize': 'fit'},
                'large': {'w': 144, 'h': 230, 'resize': 'fit'},
                'medium': {'w': 144, 'h': 230, 'resize': 'fit'},
                'thumb': {'w': 144, 'h': 144, 'resize': 'crop'}
            },
            'features': {'orig': {'faces': []}, 'small': {'faces': []}, 'large': {'faces': []}, 'medium': {'faces': []}}
        }]
    },
    'extended_entities': {
        'media': [{
            'id': 946801863734759424,
            'id_str': '946801863734759424',
            'indices': [109, 132],
            'media_url': 'http://pbs.twimg.com/media/DSO3R1iWkAAqOCG.jpg',
            'media_url_https': 'https://pbs.twimg.com/media/DSO3R1iWkAAqOCG.jpg',
            'url': 'https://t.co/FmY3K9NUCI',
            'display_url': 'pic.twitter.com/FmY3K9NUCI',
            'expanded_url': 'https://twitter.com/EvaFarohi/status/946801878649790464/photo/1',
            'type': 'photo',
            'sizes': {
                'small': {'w': 144, 'h': 230, 'resize': 'fit'},
                'large': {'w': 144, 'h': 230, 'resize': 'fit'},
                'medium': {'w': 144, 'h': 230, 'resize': 'fit'},
                'thumb': {'w': 144, 'h': 144, 'resize': 'crop'}
            },
            'features': {'orig': {'faces': []}, 'small': {'faces': []}, 'large': {'faces': []}, 'medium': {'faces': []}}
        }]
    },
    'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 3072202492,
        'id_str': '3072202492',
        'name': 'Eva-Maria Farohi',
        'screen_name': 'EvaFarohi',
        'location': 'Wien,Niederösterreich,Mallorca',
        'description': 'Autorin,Malerin',
        'url': 'http://t.co/OTVn8mKStC',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/OTVn8mKStC',
                    'expanded_url': 'http://www.farohi.at',
                    'display_url': 'farohi.at',
                    'indices': [0, 22]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 5675,
        'friends_count': 3600,
        'listed_count': 225,
        'created_at': 'Thu Mar 05 11:40:08 +0000 2015',
        'favourites_count': 80118,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 87364,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': 'C0DEED',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/607093111383302144/yIjV-Uz4_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/607093111383302144/yIjV-Uz4_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/3072202492/1444217269',
        'profile_link_color': '1DA1F2',
        'profile_sidebar_border_color': 'C0DEED',
        'profile_sidebar_fill_color': 'DDEEF6',
        'profile_text_color': '333333',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': true,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 1,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946801878649790464',
    'queued_at': 1514570134655,
    'timeline_id': '7823fd6a-ecc1-11e7-885b-6fd6eda3dde3'
}, {
    'created_at': 'Fri Dec 29 17:51:04 +0000 2017',
    'id': 946800750054821888,
    'id_str': '946800750054821888',
    'text': '#Kindle - &gt; Now available HAVE NO SHAME for those who believe love is color blind #Historical https://t.co/k5CEpnpwnn',
    'truncated': false,
    'entities': {
        'hashtags': [{'text': 'Kindle', 'indices': [0, 7]}, {'text': 'Historical', 'indices': [85, 96]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/k5CEpnpwnn',
            'expanded_url': 'http://amzn.to/16TaOSZ',
            'display_url': 'amzn.to/16TaOSZ',
            'indices': [97, 120]
        }]
    },
    'source': '<a href="https://www.socialoomph.com" rel="nofollow">SocialOomph</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 27873266,
        'id_str': '27873266',
        'name': 'Melissa Foster',
        'screen_name': 'Melissa_Foster',
        'location': 'Everywhere:-)',
        'description': 'Mom to 6, NYT & USA Today bestselling author ☼LOVE sweets ☼ books ☼ helping others ☼ life ☼ sharing smiles ☼ romance',
        'url': 'https://t.co/CQ7N819pQ3',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'https://t.co/CQ7N819pQ3',
                    'expanded_url': 'http://www.melissafoster.com',
                    'display_url': 'melissafoster.com',
                    'indices': [0, 23]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 69496,
        'friends_count': 38420,
        'listed_count': 2228,
        'created_at': 'Tue Mar 31 13:51:44 +0000 2009',
        'favourites_count': 2172,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 346784,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': 'F5FCFF',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/2596088900/tqkuamg9t83n7r614gg3_normal.jpeg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/2596088900/tqkuamg9t83n7r614gg3_normal.jpeg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/27873266/1514817677',
        'profile_link_color': '8F112B',
        'profile_sidebar_border_color': 'FFFFFF',
        'profile_sidebar_fill_color': 'F7F9FA',
        'profile_text_color': '82102C',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946800750054821888',
    'queued_at': 1514569865700,
    'timeline_id': 'd7d4a166-ecc0-11e7-9261-6508ea709316'
}, {
    'created_at': 'Fri Dec 29 17:44:11 +0000 2017',
    'id': 946799018646097920,
    'id_str': '946799018646097920',
    'text': 'LOVE BY DAWN #book 2 in the Blue Thunder series #asmsg #kindle #ibook #ian1 https://t.co/IfEyI2bhqH https://t.co/I06OABpLOF',
    'truncated': false,
    'entities': {
        'hashtags': [{'text': 'book', 'indices': [13, 18]}, {'text': 'asmsg', 'indices': [48, 54]}, {
            'text': 'kindle',
            'indices': [55, 62]
        }, {'text': 'ibook', 'indices': [63, 69]}, {'text': 'ian1', 'indices': [70, 75]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/IfEyI2bhqH',
            'expanded_url': 'http://spangaloo.com/books.php?bid=6',
            'display_url': 'spangaloo.com/books.php?bid=6',
            'indices': [76, 99]
        }],
        'media': [{
            'id': 946799016179785728,
            'id_str': '946799016179785728',
            'indices': [100, 123],
            'media_url': 'http://pbs.twimg.com/media/DSO0sFkV4AA0sH4.jpg',
            'media_url_https': 'https://pbs.twimg.com/media/DSO0sFkV4AA0sH4.jpg',
            'url': 'https://t.co/I06OABpLOF',
            'display_url': 'pic.twitter.com/I06OABpLOF',
            'expanded_url': 'https://twitter.com/Spangaloo/status/946799018646097920/photo/1',
            'type': 'photo',
            'sizes': {
                'small': {'w': 600, 'h': 300, 'resize': 'fit'},
                'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                'medium': {'w': 600, 'h': 300, 'resize': 'fit'},
                'large': {'w': 600, 'h': 300, 'resize': 'fit'}
            },
            'features': {
                'small': {'faces': [{'x': 139, 'y': 119, 'h': 43, 'w': 43}]},
                'medium': {'faces': [{'x': 139, 'y': 119, 'h': 43, 'w': 43}]},
                'large': {'faces': [{'x': 139, 'y': 119, 'h': 43, 'w': 43}]},
                'orig': {'faces': [{'x': 139, 'y': 119, 'h': 43, 'w': 43}]}
            }
        }]
    },
    'extended_entities': {
        'media': [{
            'id': 946799016179785728,
            'id_str': '946799016179785728',
            'indices': [100, 123],
            'media_url': 'http://pbs.twimg.com/media/DSO0sFkV4AA0sH4.jpg',
            'media_url_https': 'https://pbs.twimg.com/media/DSO0sFkV4AA0sH4.jpg',
            'url': 'https://t.co/I06OABpLOF',
            'display_url': 'pic.twitter.com/I06OABpLOF',
            'expanded_url': 'https://twitter.com/Spangaloo/status/946799018646097920/photo/1',
            'type': 'photo',
            'sizes': {
                'small': {'w': 600, 'h': 300, 'resize': 'fit'},
                'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                'medium': {'w': 600, 'h': 300, 'resize': 'fit'},
                'large': {'w': 600, 'h': 300, 'resize': 'fit'}
            },
            'features': {
                'small': {'faces': [{'x': 139, 'y': 119, 'h': 43, 'w': 43}]},
                'medium': {'faces': [{'x': 139, 'y': 119, 'h': 43, 'w': 43}]},
                'large': {'faces': [{'x': 139, 'y': 119, 'h': 43, 'w': 43}]},
                'orig': {'faces': [{'x': 139, 'y': 119, 'h': 43, 'w': 43}]}
            }
        }]
    },
    'source': '<a href="http://xyzwp.com" rel="nofollow">myDatabase</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 1899314857,
        'id_str': '1899314857',
        'name': 'Spangaloo',
        'screen_name': 'Spangaloo',
        'location': 'Brisbane',
        'description': 'Spangaloo is the home for Great Quality EBOOKS WE are all about promoting Authors and Books we follow back',
        'url': 'http://t.co/MtWg1ElMFQ',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/MtWg1ElMFQ',
                    'expanded_url': 'http://spangaloo.com',
                    'display_url': 'spangaloo.com',
                    'indices': [0, 22]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 9874,
        'friends_count': 9871,
        'listed_count': 861,
        'created_at': 'Tue Sep 24 05:11:01 +0000 2013',
        'favourites_count': 1,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 307799,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': 'C0DEED',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': true,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/378800000500827433/266de3b99efd6be02b259e80a65f7b2b_normal.png',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/378800000500827433/266de3b99efd6be02b259e80a65f7b2b_normal.png',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1899314857/1403314085',
        'profile_link_color': '0084B4',
        'profile_sidebar_border_color': '000000',
        'profile_sidebar_fill_color': 'DDEEF6',
        'profile_text_color': '333333',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946799018646097920',
    'queued_at': 1514569453026,
    'timeline_id': 'e1dbaa5c-ecbf-11e7-8ca0-9b4ee8d7caa1'
}, {
    'created_at': 'Fri Dec 29 17:42:30 +0000 2017',
    'id': 946798595600154624,
    'id_str': '946798595600154624',
    'text': '#Kindle #Book on #Amazon\n\n"If you are looking for a guide to reach this state of acceptance of yourself and others,… https://t.co/3xREYHVopT',
    'truncated': true,
    'entities': {
        'hashtags': [{'text': 'Kindle', 'indices': [0, 7]}, {
            'text': 'Book',
            'indices': [8, 13]
        }, {'text': 'Amazon', 'indices': [17, 24]}],
        'symbols': [],
        'user_mentions': [],
        'urls': [{
            'url': 'https://t.co/3xREYHVopT',
            'expanded_url': 'https://twitter.com/i/web/status/946798595600154624',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [117, 140]
        }]
    },
    'source': '<a href="https://www.socialoomph.com" rel="nofollow">SocialOomph</a>',
    'in_reply_to_status_id': null,
    'in_reply_to_status_id_str': null,
    'in_reply_to_user_id': null,
    'in_reply_to_user_id_str': null,
    'in_reply_to_screen_name': null,
    'user': {
        'id': 317519945,
        'id_str': '317519945',
        'name': '4 Free eBooks | Book Promoter & Bookworm',
        'screen_name': '4FreeEBooks',
        'location': 'USA',
        'description': '𝔹𝐞𝐬𝐭 #𝐁𝐨𝐨𝐤𝐬📚𝐨𝐧 #𝐊𝐢𝐧𝐝𝐥𝐞 &More! 📚𝒜𝐰𝐞𝐬𝐨𝐦𝐞 #𝐀𝐮𝐭𝐡𝐨𝐫𝐬 & #𝐖𝐫𝐢𝐭𝐞𝐫𝐬 𝐋𝐢𝐬𝐭 𝐟𝐫𝐞𝐞 #𝐞𝐛𝐨𝐨𝐤𝐬 𝟒𝐟𝐫𝐞𝐞! 👌 #𝕎𝕣𝕚𝕥𝕚𝕟𝕘  & #𝔹𝕠𝕠𝕜ℙ𝕣𝕠𝕞𝕠𝕥𝕚𝕠𝕟𝕤 #𝕄𝕠𝕔𝕜𝕌𝕡𝕤  AMZ Affiliate RTs not necc our views',
        'url': 'http://t.co/sMbo0lkRHK',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/sMbo0lkRHK',
                    'expanded_url': 'http://ContentMo.com',
                    'display_url': 'ContentMo.com',
                    'indices': [0, 22]
                }]
            }, 'description': {'urls': []}
        },
        'protected': false,
        'followers_count': 24642,
        'friends_count': 17967,
        'listed_count': 778,
        'created_at': 'Wed Jun 15 01:57:34 +0000 2011',
        'favourites_count': 261,
        'utc_offset': null,
        'time_zone': null,
        'geo_enabled': false,
        'verified': false,
        'statuses_count': 268952,
        'lang': null,
        'contributors_enabled': false,
        'is_translator': false,
        'is_translation_enabled': false,
        'profile_background_color': '294D22',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme5/bg.gif',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme5/bg.gif',
        'profile_background_tile': false,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/975314883121119232/u1el4l7x_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/975314883121119232/u1el4l7x_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/317519945/1424751993',
        'profile_link_color': 'DD2E44',
        'profile_sidebar_border_color': '829D5E',
        'profile_sidebar_fill_color': '99CC33',
        'profile_text_color': '3E4415',
        'profile_use_background_image': true,
        'has_extended_profile': false,
        'default_profile': false,
        'default_profile_image': false,
        'can_media_tag': true,
        'followed_by': false,
        'following': false,
        'follow_request_sent': false,
        'notifications': false,
        'translator_type': 'none'
    },
    'geo': null,
    'coordinates': null,
    'place': null,
    'contributors': null,
    'is_quote_status': false,
    'retweet_count': 0,
    'favorite_count': 0,
    'favorited': false,
    'retweeted': false,
    'possibly_sensitive': false,
    'lang': 'en',
    'network': 'twitter',
    'entity_id': 'twitter:946798595600154624',
    'queued_at': 1514569352068,
    'timeline_id': 'a5aeadcc-ecbf-11e7-83a4-cd362fa7dda0'
}]